//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductivityApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public long ID { get; set; }
        public string TaskName { get; set; }
        public long TaskValue { get; set; }
        public string TaskDate { get; set; }
    }
}
